name: THtest
favicon: null
layout_spectrum: 0.6489093427080661
typography_spectrum: 0.7780022681690753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9b8b8'
    - '#850838'
    - '#09538f'
    - '#f9f8f8'
    - '#5f90b7'
  brandStrength: 0.5163207000587136
  lightness: 0.3130105249583721
  saturation: 0.595877073938027
  rhythmicContrast: 0.6397371226921678
purpose: []
